export const weatherCodes: { [key: number]: { emoji: string; description: string } } = {
  0: { emoji: '☀️', description: 'Ciel dégagé' },
  1: { emoji: '🌤️', description: 'Principalement dégagé' },
  2: { emoji: '⛅', description: 'Partiellement nuageux' },
  3: { emoji: '☁️', description: 'Nuageux' },
  45: { emoji: '🌫️', description: 'Brouillard' },
  48: { emoji: '🌫️', description: 'Brouillard givrant' },
  51: { emoji: '🌦️', description: 'Bruine légère' },
  53: { emoji: '🌦️', description: 'Bruine modérée' },
  55: { emoji: '🌦️', description: 'Bruine dense' },
  61: { emoji: '🌧️', description: 'Pluie légère' },
  63: { emoji: '🌧️', description: 'Pluie modérée' },
  65: { emoji: '🌧️', description: 'Pluie forte' },
  71: { emoji: '🌨️', description: 'Neige légère' },
  73: { emoji: '🌨️', description: 'Neige modérée' },
  75: { emoji: '🌨️', description: 'Neige forte' },
  77: { emoji: '❄️', description: 'Grains de neige' },
  80: { emoji: '🌦️', description: 'Averses légères' },
  81: { emoji: '🌦️', description: 'Averses modérées' },
  82: { emoji: '🌦️', description: 'Averses fortes' },
  85: { emoji: '🌨️', description: 'Averses de neige légères' },
  86: { emoji: '🌨️', description: 'Averses de neige fortes' },
  95: { emoji: '⛈️', description: 'Orage' },
  96: { emoji: '⛈️', description: 'Orage avec grêle légère' },
  99: { emoji: '⛈️', description: 'Orage avec grêle forte' },
};
